name: data-2A
channels:
  - default
  - conda-forge
dependencies:
  - numpy
  - pandas
  - geopandas
  - pip
  - matplotlib
  - seaborn
  - scikit-learn
  - bs4
  - ipykernel
  - nltk
  - jupyterlab
  - selenium
  - flake8