name: data-2A
channels:
  - default
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - pandas
  - geopandas
  - pip
  - matplotlib
  - seaborn
  - scikit-learn
  - bs4
  - lxml
  - ipykernel
  - nltk
  - jupyterlab
  - selenium
  - flake8
  - wordcloud
  - pyahocorasick
  - openpyxl
  - xlrd
  - pip:
    - contractions
    - google_trans_new